strips = [
    horizontally_concatenated_images(
        load_images(paths, use_cache=True, show_progress=True)
    )
    for paths in [
        [
            "images_giveaway/hc_help_dogs_1_0.png",
            "images_giveaway/hc_help_dogs_1_1.png",
            "images_giveaway/hc_help_dogs_1_2.png",
            "images_giveaway/hc_help_dogs_1_3.png",
        ],
        [
            "images_giveaway/hc_help_dogs_2_0.png",
            "images_giveaway/hc_help_dogs_2_1.png",
            "images_giveaway/hc_help_dogs_2_2.png",
            "images_giveaway/hc_help_dogs_2_3.png",
        ],
        [
            "images_giveaway/hc_lipstick_gandalf_0.png",
            "images_giveaway/hc_lipstick_gandalf_1.png",
            "images_giveaway/hc_lipstick_gandalf_2.png",
            "images_giveaway/hc_lipstick_gandalf_3.png",
        ],
        [
            "images_giveaway/hc_nyan_0.png",
            "images_giveaway/hc_nyan_1.png",
            "images_giveaway/hc_nyan_2.png",
            "images_giveaway/hc_nyan_3.png",
        ],
        [
            "images_giveaway/hc_pentagram_0.png",
            "images_giveaway/hc_pentagram_1.png",
            "images_giveaway/hc_pentagram_2.png",
            "images_giveaway/hc_pentagram_3.png",
        ],
        [
            "images_giveaway/hc_playground_bio_0.png",
            "images_giveaway/hc_playground_bio_1.png",
            "images_giveaway/hc_playground_bio_2.png",
            "images_giveaway/hc_playground_bio_3.png",
        ],
        [
            "images_giveaway/hc_playground_qr_0.png",
            "images_giveaway/hc_playground_qr_1.png",
            "images_giveaway/hc_playground_qr_2.png",
            "images_giveaway/hc_playground_qr_3.png",
        ],
        [
            "images_giveaway/hc_russian_mario_0.png",
            "images_giveaway/hc_russian_mario_1.png",
            "images_giveaway/hc_russian_mario_2.png",
            "images_giveaway/hc_russian_mario_3.png",
        ],
        [
            "images_giveaway/hc_walter_thomas_0.png",
            "images_giveaway/hc_walter_thomas_1.png",
            "images_giveaway/hc_walter_thomas_2.png",
            "images_giveaway/hc_walter_thomas_3.png",
        ],
        [
            "images_giveaway/hidden_chicken_0.png",
            "images_giveaway/hidden_chicken_1.png",
            "images_giveaway/hidden_chicken_2.png",
            "images_giveaway/hidden_chicken_3.png",
        ],
        [
            "images_giveaway/q_chicken2_0.png",
            "images_giveaway/q_chicken2_1.png",
            "images_giveaway/q_chicken2_2.png",
            "images_giveaway/q_chicken2_3.png",
        ],
        [
            "images_giveaway/q_mikubest_0.png",
            "images_giveaway/q_mikubest_1.png",
            "images_giveaway/q_mikubest_2.png",
            "images_giveaway/q_mikubest_3.png",
        ],
        [
            "images_giveaway/q_nyanjungle_0.png",
            "images_giveaway/q_nyanjungle_1.png",
            "images_giveaway/q_nyanjungle_2.png",
            "images_giveaway/q_nyanjungle_3.png",
        ],
        [
            "images_giveaway/q_playring_0.png",
            "images_giveaway/q_playring_1.png",
            "images_giveaway/q_playring_2.png",
            "images_giveaway/q_playring_3.png",
        ],
        [
            "images_giveaway/tanky0.png",
            "images_giveaway/tanky1.png",
            "images_giveaway/tanky2.png",
            "images_giveaway/tanky3.png",
        ],
    ]
]
pages = [vertically_concatenated_images(x) for x in split_into_sublists(strips, 3)]
save_images(
    pages,
    make_directory("giveaway_hidden_printables") + "/page_%i",
    show_progress=True,
)
